# Generated by Django 4.2.7 on 2023-11-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='block count')),
                ('forger', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='forger')),
                ('last_hash', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='last hash')),
                ('signature', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='signature')),
                ('timestamp', models.IntegerField(blank=True, default=None, null=True, verbose_name='signature')),
                ('transactions', models.IntegerField(blank=True, default=None, null=True, verbose_name='transactions')),
            ],
        ),
    ]
