# Generated by Django 4.2.7 on 2023-11-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0002_alter_block_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='id',
            field=models.CharField(default=None, max_length=255, primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
