# Generated by Django 4.2.7 on 2023-11-07 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0004_alter_block_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'verbose_name': 'Block', 'verbose_name_plural': 'Blocks'},
        ),
    ]
