# Generated by Django 4.2.7 on 2023-11-07 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collections',
            name='address_receiver',
        ),
    ]
