# Generated by Django 4.2.7 on 2023-11-08 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='amount'),
        ),
    ]
