# Generated by Django 4.2.7 on 2023-11-06 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='key')),
                ('description', models.TextField(blank=True, default=None, null=True, verbose_name='description')),
                ('fee', models.IntegerField(blank=True, default=0, null=True, verbose_name='fee')),
            ],
            options={
                'verbose_name': 'Type Transfer',
                'verbose_name_plural': 'Types Transfer',
            },
        ),
    ]
