# Generated by Django 4.2.7 on 2023-11-06 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typetransfer',
            name='id',
        ),
        migrations.AlterField(
            model_name='typetransfer',
            name='key',
            field=models.CharField(default=None, max_length=255, primary_key=True, serialize=False, verbose_name='key'),
        ),
    ]
