# Generated by Django 4.2.7 on 2023-11-06 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='signature',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='signature'),
        ),
    ]
