# Generated by Django 4.2.7 on 2023-11-07 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_signature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='type_transaction',
        ),
    ]
