# Generated by Django 4.2.7 on 2023-11-07 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_remove_typetransfer_id_alter_typetransfer_key'),
        ('transactions', '0003_remove_transaction_type_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='type_transaction',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='settings.typetransfer'),
        ),
    ]
