# Generated by Django 4.2.7 on 2023-11-06 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.CharField(default=None, max_length=255, primary_key=True, serialize=False, verbose_name='id')),
                ('mnemonic', models.TextField(blank=True, default=None, null=True, verbose_name='mnemonic')),
                ('address', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='address')),
                ('public_key', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='public key')),
                ('balance', models.IntegerField(blank=True, default=0, null=True, verbose_name='balance')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
            },
        ),
    ]
