# Generated by Django 4.2.7 on 2023-11-06 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_alter_wallet_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='private_key',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='private key'),
        ),
    ]
