# Generated by Django 4.2.7 on 2023-11-06 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0003_wallet_private_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='signature',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='signature'),
        ),
    ]
