# Generated by Django 4.2.7 on 2023-11-06 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0004_wallet_signature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='signature',
        ),
    ]
