# Generated by Django 4.2.7 on 2023-11-07 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0005_remove_wallet_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='called_exchange',
            field=models.BooleanField(default=False, verbose_name='called exchange'),
        ),
    ]
