from dataclasses import dataclass


@dataclass
class TypeTransfer:
    CREATE_ASSET = 'CREATE_ASSET'
    EXCHANGE = 'EXCHANGE'
    STAKE = 'STAKE'
    TRANSFER = 'TRANSFER'
    UPDATE_ASSET = 'UPDATE_ASSET'
    CANCEL_REQUEST = 'CANCEL_REQUEST'
    REQUEST = 'REQUEST'
    RESPONSE_TO_REQUEST = 'RESPONSE_TO_REQUEST'
    CREATE_COLLECTION = 'CREATE_COLLECTION'
    UPDATE_COLLECTION = 'UPDATE_COLLECTION'

